INSERT INTO SHELF (SHELFNAME, DESCRIPTION)
VALUES ('S1', 'First shelf');

INSERT INTO CUSTOMER (LASTNAME, DATEOFBIRTH, LIBRARYNUMBER)
VALUES ('Doe', SYSDATE, 1);

INSERT INTO BOOK (ISBN, TITLE, AUTHORLASTNAME, SHELFNAME)
VALUES ('123456789', '1984', 'Orwell', 'S1');

INSERT INTO RENTAL (CUSTOMERLASTNAME, BOOKISBN, RENTDATE, RETURNDATE)
VALUES ('Doe', '123456789', SYSDATE, SYSDATE);
