INSERT INTO SHELF (SHELFNAME, DESCRIPTION) VALUES ("S1", "First shelf");
INSERT INTO CUSTOMER (LASTNAME, DATEOFBIRTH, LIBRARYNUMBER ) VALUES ("Does", SYSTIMESTAMP, 1);
INSERT INTO BOOK (ISBN, TITLE , AUTHORLASTNAME, SHELFNAME) VALUES ("123456789", "1984", "Orwell","S1");
INSERT INTO RENTAL(CUSTOMERLASTNAME, BOOKISBN, RENTDATE) VALUES ("DOE", "1234567890", SYSTIMESTAMP);